# fly.toml app configuration file generated for lookuplibrary on 2023-10-23T21:22:28-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lookuplibrary"
primary_region = "iad"

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
